### ISSUE TITLE
Compile with polarssl 1.3.7

### ISSUE THREAD

**Issue by nescribal** [native-toolkit/curl#1]
Hi,

I've made some tests and I compiled this version of curl with polarssl 1.3.7, mostly because it supports SSLv2, SSLv3 and TLSv1.2 (which axtls don't).

I could pushit if you want.

**Comment by jgranick** [comment]
Do you still have that code?

**Comment by nescribal** [comment]
I could send my test project, or maybe the version of polarssl I've used?

**Comment by jgranick** [comment]
Updated to mbedTLS, thank you :smile:
